### Teste
GET http://localhost:3003/ping

### Turma
POST http://localhost:3003/turma
Content-Type: application/json

{
    "id": "5",
    "nome": "Lemos",
    "tipo":"noturno"
}

### Estudante
POST http://localhost:3003/estudante
Content-Type: application/json 

{
    "id": 9,
    "nome": "Lia",
    "email": "lia@email.com",
    "data_nasc": "1995-03-07",
    "hobbies": "Familia",
    "turma_id": 2
}


### Docente
POST http://localhost:3003/docente
Content-Type: application/json 

{
    "id": 4,
    "nome": "Luiz",
    "email": "luiz@email.com",
    "data_nasc": "1987-06-14",
    "especialidades": ["JS", "CSS", "REACT"],
    "turma_id": 3
}

### ATUALIZAR DOCENTE
PUT  http://localhost:3003/docente
Content-Type: application/json

{
    "docente_id": 1,
    "turma_id": 3
}

### ATUALIZAR ESTUDANTE
PUT  http://localhost:3003/estudante
Content-Type: application/json

{
    "estudante_id": 1,

    "id": "3",
    "nome": "Bianca",
    "email": "bianca@email.com",
    "data_nasc": "1992-04-03",
    "hobbies": ["Gastronomia", "Yoga", "Budismo"],

    "turma_id": 3
}

### ATUALIZAR DOCENTE
POST http://localhost:3003/docente
Content-Type: application/json 

{
    "id": "1",
    "nome": "Manuela",
    "email": "manuela@email.com",
    "data_nasc": "1990-06-07",
    "especialidades": ["CSS", "MySQL", "React"],
    "turma_id": "1"
}