### Teste
GET http://localhost:3003/ping

### Turma
POST http://localhost:3003/turma
Content-Type: application/json

{
    "id": "4",
    "nome": "machado",
    "tipo":"noturno"
}

### Estudante
POST http://localhost:3003/estudante
Content-Type: application/json 

{
    "id": "3",
    "nome": "Bianca",
    "email": "bianca@email.com",
    "data_nasc": "1992-04-03",
    "hobbies": ["Gastronomia", "Yoga", "Budismo"],
    "turma_id": 3
}